apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    env: production
    owner: mahmoud
    webserver: nginx

spec: 
  containers: 
  - name: pod-nginx-container 
    image: nginx  
    ports:  
    - containerPort: 80
      
      